import type { Walkthrough } from "./types";

export const walkthroughs: Walkthrough[] = [
  {
    id: "sample",
    title: "Build a verified sample quest",
    shortTitle: "Verified sample quest",
    summary: "See the complete Codex build loop: one explicit scope, automated proof, real Godot playtesting, human confirmation, and persistent completion.",
    proves: ["Official Codex SDK implementation", "Exact file boundaries", "Automated verification", "Real Godot playtesting", "Human confirmation", "Persistent completion"],
    steps: [
      { id: "open-world", title: "Open the sample Project World", summary: "Forge opens a prepared, resettable workspace and makes the next playable quest visible.", why: "The creator begins from project context instead of an empty prompt.", systems: ["Creator", "Forge"], evidenceId: "launchpad", technicalProof: "The default v0.2 launch resolves the protected sample workspace without changing it." },
      { id: "select-quest", title: "Select Enemy Targeting", summary: "The roadmap points to one visible mechanic: approach the enemy, see it chase, then retreat and see it stop.", why: "A quest describes a result the creator can understand and play.", systems: ["Creator", "Forge"], evidenceId: "quest-forge", technicalProof: "The prepared quest and plan bind the outcome to three approved files and explicit acceptance criteria." },
      { id: "review-contract", title: "Review the bounded Quest Forge contract", summary: "Quest Forge shows what changes, which files Codex may touch, how Forge will verify it, and what the creator must observe.", why: "Approval is meaningful only when scope and proof are visible first.", systems: ["Creator", "Forge"], evidenceId: "quest-forge", technicalProof: "Nothing changes until the exact approval route accepts the current prepared plan." },
      { id: "approve-codex", title: "Approve the real Codex implementation", summary: "The official Codex SDK works inside the approved task. Codex can modify only the approved files, and Forge reviews the actual boundary afterward.", why: "A finished coding turn is evidence to inspect, not automatic quest success.", systems: ["Creator", "Codex", "Forge"], evidenceId: "codex-build", technicalProof: "Task 7 changed main.tscn, scripts/enemy.gd, and scripts/verify_fixture.gd with zero unexpected files." },
      { id: "review-proof", title: "Review automated proof", summary: "Forge checks the diff, file boundary, approved commands, and Godot behavior. These checks prove the project stayed healthy and bounded.", why: "Technical health matters, but it cannot decide whether the mechanic feels correct.", systems: ["Forge", "Godot"], evidenceId: "automated-proof", technicalProof: "Task 7 recorded CONDITIONAL PASS before creator confirmation and final PASS only afterward." },
      { id: "play-result", title: "Play the result in Godot", summary: "The creator moves toward and away from the enemy and personally observes IDLE → CHASING → IDLE. Closing the game alone does not confirm success.", why: "Gameplay judgment belongs to the person directing the game.", systems: ["Creator", "Godot"], evidenceId: "playtest", technicalProof: "The real held-key playtest remained a manual release gate because automation could not truthfully perform the observation." },
      { id: "confirm", title: "Confirm success and see persistent completion", summary: "Only explicit confirmation changes the roadmap, records final PASS, and writes the Chronicle event. The state survives restart.", why: "Progress becomes durable only after proof and creator judgment agree.", systems: ["Creator", "Forge"], evidenceId: "completion", technicalProof: "Task 7 reloaded the completed roadmap, preserved it through reset cancellation, then restored the clean fixture after confirmed reset." },
    ],
  },
  {
    id: "new-game",
    title: "Create a new game",
    shortTitle: "New game creation",
    summary: "See GPT-5.6 shape a small idea, then watch Forge create, verify, baseline, organize, and reopen a controlled local Godot project.",
    proves: ["GPT-5.6 structured planning", "Creator blueprint approval", "Controlled Godot project creation", "Godot verification", "Clean local Git baseline", "Persistent Project World"],
    steps: [
      { id: "describe", title: "Describe a small 2D game idea", summary: "The creator names the action, fun target, controls, and smallest playable result. Forge keeps the idea inside the supported Godot 2D boundary.", why: "A small playable promise is easier to plan and verify than an entire game.", systems: ["Creator", "Forge"], evidenceId: "launchpad", technicalProof: "Forge permits at most three focused questions across five intake topics and never opens a general chat." },
      { id: "review-blueprint", title: "Review the GPT-5.6 blueprint", summary: "GPT-5.6 proposes a structured vision, first playable milestone, and bounded roadmap for creator review.", why: "The model helps shape intent while the creator still owns the game direction.", systems: ["GPT-5.6", "Creator"], evidenceId: "blueprint", technicalProof: "The strict schema rejects absolute paths, commands, packages, dependencies, source files, and workflow claims from the model." },
      { id: "approve-creation", title: "Approve controlled project creation", summary: "Blueprint approval writes nothing. A second explicit confirmation authorizes Forge—not GPT—to create the project from a controlled starter.", why: "Planning approval and filesystem approval are separate decisions.", systems: ["Creator", "Forge"], evidenceId: "blueprint", technicalProof: "A same-origin, one-time mutation token and exact CONFIRM CREATE phrase protect the creation boundary." },
      { id: "verify", title: "Verify the Godot starter and Git baseline", summary: "Forge writes validated project records, Godot checks the real starter, and Git establishes one clean local baseline without remotes.", why: "The project starts from a known, playable, recoverable state.", systems: ["Forge", "Godot", "Git"], evidenceId: "creation", technicalProof: "Task 7 emitted FORGE_TOP_DOWN_ARENA_VERIFY_OK and created a clean no-remote baseline before registration." },
      { id: "enter-world", title: "Enter the generated Project World", summary: "The verified starter, first playable milestone, roadmap, documents, and Chronicle load from persistent project artifacts.", why: "The project remains understandable after creation instead of collapsing back into chat history.", systems: ["Forge"], evidenceId: "generated-world", technicalProof: "The registry resolves only a canonical registered project, then Forge validates its project-local manifest and referenced artifacts." },
      { id: "explore-roadmap", title: "Explore planning-only quest briefs", summary: "Each generated quest explains intent, dependencies, scope, criteria, and proof ideas. Implementation remains intentionally unavailable in v0.2.", why: "Planned work stays honest and does not masquerade as implemented capability.", systems: ["Creator", "Forge"], evidenceId: "generated-world", technicalProof: "All generated quest implementation states are not_enabled; the sample path alone demonstrates the complete Codex build loop." },
      { id: "save-reopen", title: "Save an idea and reopen after restart", summary: "An idea seed persists as planning input and derived activity without silently changing the authoritative roadmap or Chronicle.", why: "Useful possibilities survive sessions without hijacking approved work.", systems: ["Creator", "Forge"], evidenceId: "generated-world", technicalProof: "Task 7 proved byte-identical roadmap and Chronicle hashes after idea save, clean Git, and restart restoration." },
    ],
  },
];
